name: jisho
description: A new Flutter project.

publish_to: 'none'

version: 2.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  tab_indicator_styler: ^2.0.0
  flutter_native_splash: ^2.0.5

  path_provider: ^2.0.9
  permission_handler: ^9.2.0

  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  
  path: ^1.8.0
  sqflite: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true

  assets:
    - assets/databases/

flutter_native_splash:
  color: "#42a5f5"
